apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: postgres-service
    app: demo-voting-app

spec:
  selector:
    name: postgres-pod  # name of the redis pod
    app: demo-voting-app  # name of the redis app
  ports:
  - port: 5432
    targetPort: 5432
