apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: demo-voting-app
spec:
  selector:
    name: redis-pod  # name of the redis pod
    app: demo-voting-app  # name of the redis app
  ports:
  - port: 6379
    targetPort: 6379
