apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    app: demo-voting-app

spec:
  type: NodePort
  selector:
    name: result-app-pod  # name of the result pod
    app: demo-voting-app  # name of the result app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30005
