apiVersion: v1
kind: Pod
metadata: 
    name: redis-pod
    labels: 
        name: redis-pod  # name of the pod
        app: demo-voting-app  # name of the app

spec: 
  containers:
    - name: redis
      image: redis
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 6379