apiVersion: v1
kind: Pod
metadata: 
    name: result-app-pod
    labels: 
        name: result-app-pod  # name of the pod
        app: demo-voting-app  # name of the app

spec: 
  containers:
    - name: voting-app
      image: kodekloud/examplevotingapp_result:v1
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80